name = "PottsGumbelRBMLayers"
uuid = "bcd408f2-95f5-489e-9934-d251842dc866"
authors = ["JFdCD <j.cossio.diaz@gmail.com>"]
version = "2.0.1-DEV"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
RestrictedBoltzmannMachinesHDF5 = "d76020e8-6658-45fa-bb6d-0aaddbb4b5e5"

[weakdeps]
CudaRBMs = "4e7460e3-fd1b-4f88-90fa-49c1b80b3e77"

[extensions]
PottsGumbelCUDAExt = "CudaRBMs"

[compat]
CudaRBMs = "1"
EllipsisNotation = "1"
RestrictedBoltzmannMachines = "3"
RestrictedBoltzmannMachinesHDF5 = "2"
julia = "1.9"
