name = "PottsGumbelRBMLayers"
uuid = "bcd408f2-95f5-489e-9934-d251842dc866"
authors = ["JFdCD <j.cossio.diaz@gmail.com>"]
version = "1.0.0-DEV"

[deps]
CudaRBMs = "4e7460e3-fd1b-4f88-90fa-49c1b80b3e77"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"

[compat]
julia = "1.8.3"
